/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.wz.plugin

import org.gradle.testfixtures.ProjectBuilder
import spock.lang.Specification

/**
 * A simple unit test for the 'com.wz.plugin.greeting' plugin.
 */
class HelloPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("com.wz.plugin.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
